# Generated by Django 5.0 on 2024-08-08 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_number', models.PositiveIntegerField(unique=True, verbose_name='Volume Number')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('article_type', models.CharField(max_length=100)),
                ('authors', models.TextField()),
                ('publication_date', models.DateField()),
                ('publication_details', models.CharField(max_length=100)),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='journalApis.volume')),
            ],
        ),
    ]
