# Generated by Django 5.0 on 2024-10-12 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalApis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volume',
            name='number_of_issues',
        ),
        migrations.AlterField(
            model_name='volume',
            name='issue_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Issue Number'),
        ),
    ]
