# Generated by Django 5.0 on 2024-09-07 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journalApis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_type',
        ),
        migrations.RemoveField(
            model_name='article',
            name='volume',
        ),
        migrations.DeleteModel(
            name='ArticleType',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Volume',
        ),
    ]
