# Generated by Django 5.0 on 2024-08-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalApis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volume',
            name='volume_number',
            field=models.IntegerField(unique=True, verbose_name='Volume Number'),
        ),
    ]
