# Generated by Django 5.0 on 2024-10-13 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalApis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalimage',
            name='journal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='journalApis.journal'),
        ),
    ]
