# Generated by Django 5.0 on 2024-08-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalApis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='author',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='doi',
        ),
        migrations.AddField(
            model_name='pdf',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pdf',
            name='doi',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pdf',
            name='language',
            field=models.CharField(default='Not Specified', max_length=50),
        ),
    ]
