# Generated by Django 5.0 on 2024-08-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalApis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='aim_identifier',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='issn_number',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='publishers_name',
            field=models.CharField(blank=True, max_length=1055, null=True),
        ),
    ]
