# Generated by Django 5.0 on 2024-08-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalApis', '0002_alter_volume_volume_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volume',
            name='volume_number',
            field=models.PositiveIntegerField(unique=True, verbose_name='Volume Number'),
        ),
    ]
