# Generated by Django 5.0 on 2024-08-04 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalApis', '0002_remove_journal_author_remove_journal_doi_pdf_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='volume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='journalApis.volume'),
        ),
    ]
