# Generated by Django 5.0 on 2024-10-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalApis', '0003_alter_journal_issn_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='link',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
