# Generated by Django 5.0 on 2024-11-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalApis', '0005_rename_license_info_article_license_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='license_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
