# Generated by Django 5.0 on 2024-10-10 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journalApis', '0005_volume_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volume',
            name='journal',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Volume',
        ),
    ]
