# Generated by Django 5.0 on 2024-10-10 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalApis', '0006_remove_volume_journal_delete_article_delete_volume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_number', models.PositiveIntegerField(verbose_name='Volume Number')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='journalApis.journal')),
            ],
            options={
                'unique_together': {('journal', 'volume_number')},
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('authors', models.TextField()),
                ('keywords', models.TextField()),
                ('publication_date', models.DateField()),
                ('volume', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='journalApis.volume')),
            ],
        ),
    ]
