# Generated by Django 5.0 on 2024-10-10 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalApis', '0007_volume_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='articles/pdfs/'),
        ),
    ]
