# Generated by Django 5.0 on 2024-11-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalApis', '0007_lastprocessedjournal_date_processed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_type',
            field=models.CharField(blank=True, max_length=1050, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='doi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='electronic_issn',
            field=models.CharField(blank=True, max_length=1050, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='print_issn',
            field=models.CharField(blank=True, max_length=1050, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='publisher',
            field=models.CharField(blank=True, max_length=1255, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.TextField(),
        ),
    ]
