# Generated by Django 5.0 on 2024-11-17 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalApis', '0008_alter_article_article_type_alter_article_doi_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalsWithoutImages',
            fields=[
            ],
            options={
                'verbose_name': 'Journal (No Image)',
                'verbose_name_plural': 'Journals (No Images)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('journalApis.journal',),
        ),
        migrations.CreateModel(
            name='JournalsWithoutVolumes',
            fields=[
            ],
            options={
                'verbose_name': 'Journal (No Volume)',
                'verbose_name_plural': 'Journals (No Volumes)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('journalApis.journal',),
        ),
        migrations.AddField(
            model_name='article',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='journalApis.journal'),
        ),
        migrations.AddIndex(
            model_name='journal',
            index=models.Index(fields=['journal_title', 'platform', 'country', 'language', 'thematic_area', 'issn_number', 'summary'], name='journalApis_journal_b3a051_idx'),
        ),
        migrations.AddIndex(
            model_name='journal',
            index=models.Index(fields=['aim_identifier'], name='journalApis_aim_ide_9b6671_idx'),
        ),
        migrations.AddIndex(
            model_name='journal',
            index=models.Index(fields=['sjr'], name='journalApis_sjr_5ff10e_idx'),
        ),
        migrations.AddIndex(
            model_name='journal',
            index=models.Index(fields=['listed_in_doaj'], name='journalApis_listed__603173_idx'),
        ),
        migrations.AddIndex(
            model_name='journal',
            index=models.Index(fields=['present_issn'], name='journalApis_present_1cc171_idx'),
        ),
        migrations.AddIndex(
            model_name='journal',
            index=models.Index(fields=['open_access_journal'], name='journalApis_open_ac_3043e3_idx'),
        ),
        migrations.AddIndex(
            model_name='journal',
            index=models.Index(fields=['publisher_in_cope'], name='journalApis_publish_32d1bc_idx'),
        ),
        migrations.AddIndex(
            model_name='journal',
            index=models.Index(fields=['online_publisher_africa'], name='journalApis_online__29f98f_idx'),
        ),
        migrations.AddIndex(
            model_name='journal',
            index=models.Index(fields=['impact_factor'], name='journalApis_impact__4b4fe6_idx'),
        ),
        migrations.AddIndex(
            model_name='journal',
            index=models.Index(fields=['h_index'], name='journalApis_h_index_764d1f_idx'),
        ),
        migrations.AddIndex(
            model_name='journal',
            index=models.Index(fields=['hosted_on_inasps'], name='journalApis_hosted__697fe5_idx'),
        ),
        migrations.AddIndex(
            model_name='journal',
            index=models.Index(fields=['google_scholar_index'], name='journalApis_google__4ad2d5_idx'),
        ),
        migrations.AddIndex(
            model_name='journalimage',
            index=models.Index(fields=['image', 'description'], name='journalApis_image_e43357_idx'),
        ),
        migrations.AddIndex(
            model_name='volume',
            index=models.Index(fields=['volume_number', 'issue_number', 'year'], name='journalApis_volume__bce674_idx'),
        ),
    ]
