# Generated by Django 5.0 on 2024-11-22 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journalApis', '0010_alter_article_publication_date_alter_article_volume'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JournalsWithoutVolumes',
        ),
        migrations.CreateModel(
            name='JournalsWithoutVolumesOrArticles',
            fields=[
            ],
            options={
                'verbose_name': 'Journal (No Volume or Article)',
                'verbose_name_plural': 'Journals (No Volumes or Articles)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('journalApis.journal',),
        ),
    ]
