# Generated by Django 5.0 on 2024-11-22 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journalApis', '0011_delete_journalswithoutvolumes_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JournalsWithoutVolumesOrArticles',
        ),
        migrations.CreateModel(
            name='JournalsWithoutVolumes',
            fields=[
            ],
            options={
                'verbose_name': 'Journal (No Volume)',
                'verbose_name_plural': 'Journals (No Volumes)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('journalApis.journal',),
        ),
    ]
