# Generated by Django 5.0 on 2024-11-26 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journalApis', '0012_delete_journalswithoutvolumesorarticles_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalsWithoutArticles',
            fields=[
            ],
            options={
                'verbose_name': 'Journal (No Articles)',
                'verbose_name_plural': 'Journals (No Articles)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('journalApis.journal',),
        ),
    ]
