# Generated by Django 5.0 on 2024-12-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalApis', '0012_delete_journalswithoutvolumesorarticles_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=2000, null=True)),
                ('email', models.CharField(blank=True, max_length=2000, null=True)),
                ('question', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JournalsWithoutArticles',
            fields=[
            ],
            options={
                'verbose_name': 'Journal (No Articles)',
                'verbose_name_plural': 'Journals (No Articles)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('journalApis.journal',),
        ),
    ]
