# Generated by Django 5.1.4 on 2025-01-28 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalApis', '0014_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='h_index',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='impact_factor',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
