# Generated by Django 5.0 on 2024-12-20 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journalApis', '0013_feedback_journalswithoutarticles'),
        ('journalApis', '0014_feedback'),
    ]

    operations = [
    ]
