# Generated by Django 5.1.4 on 2026-04-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalApis', '0015_alter_journal_h_index_alter_journal_impact_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
