# Generated by Django 5.1.4 on 2025-02-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(help_text='Title of the blog', max_length=255, unique=True)),
                ('blog_link', models.URLField(blank=True, help_text='Optional: Link to read the full blog', null=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the blog', null=True)),
                ('date_published', models.DateField(blank=True, help_text='Date when the blog was published', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
