# Generated by Django 5.1.4 on 2025-04-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
