# Generated by Django 5.1.4 on 2026-06-21 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApi', '0003_newuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='role',
        ),
    ]
