# Generated by Django 5.1.4 on 2025-01-27 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Funding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funding_title', models.CharField(help_text='Title of the funding opportunity.', max_length=1055)),
                ('organization', models.CharField(help_text='Name of the funding organization.', max_length=1055)),
                ('theme', models.CharField(help_text='Thematic area of the funding.', max_length=1055)),
                ('country', models.CharField(help_text='Country where the funding is applicable.', max_length=255)),
                ('region', models.CharField(blank=True, help_text='Region for the funding (e.g., Africa, Asia, Europe).', max_length=255, null=True)),
                ('funding_type', models.CharField(blank=True, help_text='Type of funding (e.g., Grant, Fellowship, Scholarship).', max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the funding.', null=True)),
                ('elligibility', models.TextField(blank=True, help_text='Eligibility criteria for applicants.', null=True)),
                ('grant_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount of the grant (if applicable).', max_digits=15, null=True)),
                ('application_link', models.URLField(blank=True, help_text='Link to apply for the funding.', null=True)),
                ('start_date', models.DateField(blank=True, help_text='Start date for applications.', null=True)),
                ('end_date', models.DateField(blank=True, help_text='End date for applications.', null=True)),
                ('deadline', models.DateField(blank=True, help_text='Deadline for submitting applications.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the funding opportunity currently open?')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Open', 'Open'), ('Closed', 'Closed')], default='Draft', help_text='Status of the funding opportunity.', max_length=50)),
                ('contact_email', models.EmailField(blank=True, help_text='Contact email for inquiries.', max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, help_text='Contact phone number.', max_length=20, null=True)),
                ('attachment', models.FileField(blank=True, help_text='Upload related document.', null=True, upload_to='funding_attachments/')),
                ('tags', models.CharField(blank=True, help_text='Keywords for filtering.', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this entry was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this entry was last updated.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Funding Opportunity',
                'verbose_name_plural': 'Funding Opportunities',
            },
        ),
    ]
