# Generated by Django 5.1.4 on 2025-01-27 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funding',
            name='currency',
            field=models.CharField(blank=True, choices=[('$', 'USD ($)'), ('€', 'EUR (€)'), ('£', 'GBP (£)'), ('KSh', 'KES (KSh)'), ('₹', 'INR (₹)'), ('¥', 'JPY (¥)'), ('R', 'ZAR (R)')], help_text='Currency symbol for the grant amount (e.g., $, €, £).', max_length=5, null=True),
        ),
    ]
