# Generated by Django 5.1.4 on 2025-02-02 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0002_funding_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Type of funding (e.g., Grant, Fellowship, Scholarship).', max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='funding',
            name='funding_type',
            field=models.ForeignKey(blank=True, help_text='Type of funding.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='funding.fundingtype'),
        ),
    ]
