# Generated by Django 5.1.4 on 2025-02-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0003_fundingtype_alter_funding_funding_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funding',
            old_name='grant_amount',
            new_name='grant_amount_lower',
        ),
        migrations.AddField(
            model_name='funding',
            name='grant_amount_upper',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount of the grant (if applicable).', max_digits=15, null=True),
        ),
    ]
